kind: pipeline
name: default

workspace:
  base: /book
  path: gobyexample-zh

steps:
- name: build
  image: panbook:latest
  pull: if-not-exists
  commands:
  - echo "DRONE_BRANCH:$DRONE_BRANCH"
  - echo "DRONE_COMMIT:$DRONE_COMMIT"
  - echo "DRONE_TAG:$DRONE_TAG"
  - echo "DRONE_COMMIT_MESSAGE:$DRONE_COMMIT_MESSAGE"
  - echo "DRONE_COMMIT_SHA:$DRONE_COMMIT_SHA"
  - echo "DRONE_COMMIT_REF:$DRONE_COMMIT_REF"
 
- name: publish
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - build