kind: pipeline
name: default

workspace:
  base: /book
  path: gobyexample-zh

clone:
  git:
    image: plugins/git
    tags: true
    
steps:
- name: build
  image: panbook:latest
  pull: if-not-exists
  commands:
  - DEBUG=-d make
 
- name: publish
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - build